#!/usr/bin/R

## This is a starter for the group project on Data Visualization and Binning Parameters
## You will need results files from the metabat2 binning
## The two files needed are the depth.txt file which contains data on the read coverage depth 
## per contig in the assembly.  This was generated from the Read alignment file by the first 
## stage of metabat2 run.  
##
## You will also need the binning.tsv file which is generated by the next stage of metabat2
## and contains two columns with the name of the contig and the name of the BinID
## R will generate NA values for those contigs without a binID and we will assign those to 
## a label of Unbinned

require(ggplot2)
require(RColorBrewer)

depth <- read.delim("depth.txt", header=TRUE, sep="\t")

## Note that when R reads in the depth file the column name of the variance changes because the dash could be
## a problematic character for R

head(depth)

## plotting the contig length as x and the total average depth of reads on that contig as y

## what do you notice?

pdf(file = "contigLen_vs_totalAvgDepth.pdf", width=12, height=8)

ggplot(depth, aes(contigLen, totalAvgDepth)) + geom_point(colour="steelblue") + theme_bw()

dev.off()

## Can we tell if metabat2 has done a good job of binning?
## What are the characteristics of binned contigs?
## This is a technical bioinformatics project that impacts the final data for the overrarching biological project
##
## Investigating the log10 values of the mean and variance of the depth of reads on each contig can give us clues
## Explain the results


pdf(file = "log10_depth_vs_variance_coverage.pdf", width=12, height=8)

df_plot <- depth
ggplot(df_plot, aes(x = Community_aligned.bam.sorted.bam, y = Community_aligned.bam.sorted.bam.var)) + scale_x_log10() + scale_y_log10() +
  #adding a reference line where the variance is equal to the mean (that would be a Poisson distribution)
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "red") +
  geom_point(alpha = 0.4, size = 1, color = "darkcyan") +
  labs(title = "Contig Mean Depth of Read alignments vs the Variance",
       subtitle = "Dashed line represents where the depth variance is equal to the mean",
       x = "TotalAvgDepth (log10)",
       y = "Depth Variance (log10)") + theme_minimal()

dev.off()

#Adding colour and size scales will mean the data can show much more detail
#Including labels for the binned contigs will identify their characteristics

bin_data <- read.delim("binning.tsv", header=FALSE, sep="\t")
colnames(bin_data) <- c("contigName", "BinID")
head(bin_data)

#merging the plot data frame with the binning data frame from the binning.tsv file generated by metabat2
df_final <- merge(df_plot, bin_data, by="contigName", all.x = TRUE)

head(df_final)
#rename any missing data points in the BinID column as Unbinned
df_final$BinID <- ifelse(is.na(df_final$BinID), "Unbinned", df_final$BinID)

head(df_final)

pdf("metabat_binned_contigs_characteristics.pdf", width=12, height=8)

ggplot(df_final, aes(x = Community_aligned.bam.sorted.bam, y = Community_aligned.bam.sorted.bam.var)) +
   geom_point(aes(color = BinID, size = contigLen), alpha=0.6) +
   scale_x_log10() + scale_y_log10() +
   geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "red") +
   scale_color_viridis_d(name = "Bin ID", option="turbo") +
   scale_size_continuous(range = c(0.5, 4), name = "Length (bp)") +
   labs(
      title = "Binning Results: Depth vs Variance",
      subtitle = "Coloured by metabat2 Bin ID",
      x = "TotalAvgDepth (log10)",
      y = "Depth Variance (log10)") + theme_minimal()

dev.off()

# We can make this plot clearer by introducing a pale grey colour specifically for the Unbinned contigs

actual_bins <- sort(unique(df_final$BinID[df_final$BinID != "Unbinned"]))
bin_colors <- colorRampPalette(brewer.pal(11, "Spectral"))(length(actual_bins))

names(bin_colors) <- actual_bins
final_pal <- c(bin_colors, "Unbinned" = "grey65")
df_final$alpha_val <- ifelse(df_final$BinID == "Unbinned", 0.1, 0.8)


pdf("final_metabat_binned_contigs_characteristics.pdf", width=12, height=8)

ggplot(df_final, aes(x = Community_aligned.bam.sorted.bam, y = Community_aligned.bam.sorted.bam.var)) +
   geom_point(aes(color = BinID, size = contigLen), alpha=df_final$alpha_val) +
   scale_x_log10() + scale_y_log10() +
   geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "red") +
   scale_alpha_identity(guide="none") + 
   scale_color_manual(values = final_pal, name = "Bin ID") +
   scale_size_continuous(range = c(0.5, 4), name = "Length (bp)") +
   labs(
      title = "Binning Results: Depth vs Variance",
      subtitle = "Coloured by metabat2 Bin ID",
      x = "TotalAvgDepth (log10)",
      y = "Depth Variance (log10)") + theme_minimal()

dev.off()


# What can you notice about the contigs that are either binned or unbinned?
#
# Importantly: 
# What can this tell us about the organism abundance in the bins?
