#!/bin/bash -e
#SBATCH --qos=bio-ds
#SBATCH -p bio-ds
#SBATCH -J "binning_metabat"
#SBATCH --mem=10G
#SBATCH --cpus-per-task=16
#SBATCH --job-name=metagenomics_tutorial
#SBATCH -o /gpfs/home/%u/scratch/Data/Metagenomics_tutorial/Binning/Output_Messages/Metagenomics_tutorial-%a.out
#SBATCH -e /gpfs/home/%u/scratch/Data/Metagenomics_tutorial/Binning/Error_Messages/Metagenomics_tutorial-%a.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=#<your.email@address>

module add mamba/25.3.1
source /gpfs/software/hali/mamba/25.3.1-0/etc/profile.d/mamba.sh
# check if the environment exists from a previous run and if so delete it or it will fail here
mamba env remove -n unpackenv -y || true
# (re)create the environment 
mamba create -n unpackenv -y
mamba activate unpackenv

# mamba is a faster version of anaconda/conda
# however, the binning software metabat2 uses boost C++ libraries which takes a really long time (~ 10 mins) to install on HPC
# what we can do instead is to use conda-pack to create an archived environment.  This archived environment
# is only for HPC and you would have to use mamba to fully build the environment on any other system

# to build the env for yourself use this after copying /gpfs/data/BIO-DSB/Session7/MG_workflow_2026/binning_env2.tar.gz to your scratch
# mkdir -p scratch/my_binning_env
# tar -xvf scratch/binning_env2.tar.gz -C scratch/my_binning_env
# source scratch/my_binning_env/bin/activate

# to build straightaway from the BIO-DSB dir - fastest but the environment is read-only
source /gpfs/data/BIO-DSB/Session7/MG_workshop_2026/Binning_env2/bin/activate


# Define input/output directories
GENOME_FASTA="$HOME/scratch/Metagenomics_shotgun_tutorial/RawData/CommunityScaffolds.fasta"
FASTQ_DIR="/gpfs/data/BIO-DSB/Session7/MG_workshop_2026/FASTQ/"
INPUT_DIR="$HOME/scratch/Metagenomics_shotgun_tutorial/ReadAligns/"
SCRIPT_DIR="$HOME/scratch/Metagenomics_shotgun_tutorial/Binning/scripts/"
OUTPUT_DIR="$HOME/scratch/Metagenomics_shotgun_tutorial/Binning/Bins/"

# For use in any other environment you will need to setup with the usual method 
# mamba environment setup 
# mamba env create -n binning_env -f leanbinmetabat.yaml

echo "successfully created environment from paths"

# Ensure OUTPUT_DIR exists
mkdir -p "$OUTPUT_DIR"


jgi_summarize_bam_contig_depths --referenceFasta "$GENOME_FASTA" --outputDepth depth.txt "$INPUT_DIR"Community_aligned.bam.sorted.bam

echo "defined directories, commencing depth statistics calculation"

metabat2 -t 16 -a "$HOME"/scratch/Metagenomics_shotgun_tutorial/Binning/depth.txt -i "$GENOME_FASTA" -o "$OUTPUT_DIR"/MetaBatBins --minContig 2000 --noAdd -v
echo "completed metabat2 binning process"

#renaming files which finish in .fa from metabat2 but need to finish .fasta for binspreader_protocol
for file in "$OUTPUT_DIR"/MetaBatBins*.fa; do mv $file $file"sta"; done

echo "renamed files for converting to tab delimited format"

python "$SCRIPT_DIR"/convert_fasta_bins_to_tsv_format.py --o binning.tsv "$OUTPUT_DIR"/MetaBatBins*

echo "refining current bins using the metagenomics assembly graph with our newly calculated binning.tsv"

# For this next step you will need to use the Assembly graph (.gfa) file which was generated by the assembler alongside the contig fasta
# It is provided in the GitHub for use

bin-refine "$HOME"/scratch/Metagenomics_shotgun_tutorial/Binning/CommunityScaffolds_assembly.gfa binning.tsv "$OUTPUT_DIR"binspreader-Rcorr --tmp-dir "$OUTPUT_DIR"/tmp --bin-dist -t 16 -Rcorr | tee binspreader-Rcorr.log

python "$SCRIPT_DIR"visualize_bin_dist.py -i "$OUTPUT_DIR"/binspreader-Rcorr/bin_dist.tsv -o result/dendrogram.png

python "$SCRIPT_DIR"extract_fasta_bins.py -b "$OUTPUT_DIR"/binspreader-Rcorr/binning.tsv -i "$INPUT_DIR"CommunityScaffolds.fasta -o refined_bins
cd refined_bins
for file in MetaBatBins*fasta; do mv $file "refined_"$file; done
cd ..
echo "bin refining process complete"

# these scripts could be of interest to look into in more depth
#python scripts wide2long.py, extract_fasta_bins.py, convert_fasta_bins_to_tsv_format.py


